# Informatie over opgaven wordt opgeslagen in TOML formaat
# Met de hashtag kan je deze bestanden van commentaar voorzien
# Opgaven bevatten de volgende structuur:
# naam (string, verplicht)
# text (string, optioneel)
# afbeelding (string, optioneel)
# De vraag of vragen (table, tenminste 1)

# Een vraag bevat de volgende structuur:
# text (string ; verplicht)
# afbeelding (string, optioneel)
# punten (getal ; verplicht)
# niveau (getal ; verplicht)
#     0 = R
#     1 = T1
#     2 = T2
#     3 = I

naam = "Een schakeling maken"
text = "In een schakeling zijn 3 lampen opgenomen die zijn aangesloten op een batterij. Er is 1 schakelaar waarmee lamp A en lamp B tegelijk mee worden in- en uitgeschakeld.  Er is nog een schakelaar waarmee de lamp C wordt bediend."

[vraag1]
text = "Teken een schakelschema dat bovenstaande eigenschappen heeft en label lampjes A, B en C (nb: er zijn meerdere mogelijkheden, 1 tekening is genoeg)."
punten = 3
niveau = 2

[vraag2]
text = "Teken het schakelschema nogmaals, en teken ook in de stroomkring een stroommeter waarmee de totale stroom door lamp A en B gemeten kan worden."
punten = 3
niveau = 2

[vraag3]
text = "Teken de stroomkring nog een keer; doe dat zodanig dat je aan bovenstaande eisen voldoen, maar bovendien een stroommeter kan plaatsen waarmee je de stroom door lamp B en C kunt meten."
punten = 2
niveau = 3