# Informatie over opgaven wordt opgeslagen in TOML formaat
# Met de hashtag kan je deze bestanden van commentaar voorzien
# Opgaven bevatten de volgende structuur:
# naam (string, verplicht)
# text (string, optioneel)
# afbeelding (string, optioneel)
# De vraag of vragen (table, tenminste 1)

# Een vraag bevat de volgende structuur:
# text (string ; verplicht)
# afbeelding (string, optioneel)
# punten (getal ; verplicht)
# niveau (getal ; verplicht)
#     0 = R
#     1 = T1
#     2 = T2
#     3 = I

naam = "De ballon"
text = "Marion heeft met een ballon over haar wollen trui gewreven. Daardoor is de ballon negatief geladen."

[vraag1]
text = "Hoe heten de deeltjes die daarbij zijn overgesprongen?"
punten = 1
niveau = 0

[vraag2]
text = "Zijn die deeltjes overgesprongen van de ballon naar de trui of van de trui naar de ballon?"
punten = 1
niveau = 1

[vraag3]
text = "Wat voor lading heeft haar trui gekregen?"
punten = 1
niveau = 1

[vraag4]
text = "Leg uit waardoor de ballon aan haar trui blijft ‘kleven’"
punten = 1
niveau = 1